---
title: "You can learn programming: 3 tips"
format: html
---

Hey, I'm Greta, an ESRC-funded PGT student. This means that this year I am doing an MA in Social Science Research and then I will transition to a PhD in Interdisciplinary Methods! I'm super excited about this but also I would not be here if I had not pushed myself out of my comfort zone a couple of years ago. What do I mean?

In May 2020 I was a soon-to-graduate sociology student at Warwick who realised that quantitative and computational skills can open many doors. I was trained to apply some basic statistical methods, however I did not know how I can make use of the vast amount of data generated as a by-product of our everyday activities through apps, web-browsing, etc. Thus, I decided to get a master's degree. I did not want to pursue a degree in data science as I did not believe to have the aptitude or skills, such as strong mathematical background. I searched for a compromise and I found it -- thank you [CIM](https://warwick.ac.uk/fac/cross_fac/cim/)!

Two years forward, I have successfully completed my MSc degree and worked for a year as a Data Scientist at [LIDA](https://lida.leeds.ac.uk). Sometimes I still cannot believe how far I have gone. Thus, through this blog post I want to stress that you can learn programming -- it might not be easy, but it is achievable. Below I share 3 tips that are applicable regardless of the programming language or area you choose to go after.

### You can learn programming

First things first, I think it is essential to believe that you can do it. Growth mindset is important as [mindset for programming aptitude is associated with programming practice](https://ieeexplore.ieee.org/abstract/document/6662493). Indeed, it might be hard to possess self-belief if you, like me, have never considered yourself to be into STEM. To be honest, at high school I swapped computer science module to biology because I could not understand a thing! I think I was taught Java... Thus, I had low expectations for myself, but also I wanted to test myself as I knew why I am pushing myself out of my comfort zone.

### Understand why you want to learn programming

I did not want to learn any programming language for the sake of learning it. I wanted to learn the one that would be useful for quantitative research and data science. My aim was to equip myself with skills to work with big data. Thus, I enrolled to a master's degree that suited my needs. Not only did this decision reduce [choice overload](https://thedecisionlab.com/biases/choice-overload-bias), but also increased my motivation -- I knew my why. There are many programming languages for different purposes, such as web development, data science, and software development. Knowing in which area you would like to apply your skills will help develop more focused approach to learning.

### Celebrate small wins

You might be a highly motivated person who has self-belief and knows a why. But, at least in my experience, it is still challenging to sustain them over time. Levels of motivation and self-belief might fluctuate leading to questioning of your choices. This happened and still happens to me, especially when learning new concepts. My solution is to celebrate every little victory. For instance, when I just started learning programming, I was so happy to figure out what an 'i' in a loop means! I used these little moments of 'eureka!' to appreciate my work ethic and remind myself that I am capable. This creates a loop of motivation feeding achievement and achievement boosting motivation. After all programming is about constant learning regardless of one's experience. Thus celebrating every small win might pave a way for lifelong passion that currently seems beyond your reach.









