---
title: "Cover Letter"
format: html
---

I am a master's student in social science research pursuing a PhD who also wants to share the insights that I wish someone else had shared with me. I have a diverse academic experience -- from BA in Sociology to MSc in Big Data and Digital Futures, both at Warwick -- positioning me in a unique position between STEM and social sciences/humanities. I am proud of, and passionate about, learning programming for data science, a skill that opened me a Data Scientist position. I want to share my journey and inspire others to take action to pursue their dreams. I believe one way of doing it is through writing.

For example, I wrote a [blog post](https://gretatimaite.netlify.app/publication/networking_lida/) for Leeds Institute for Data Analytics sharing my experiences of partnership building as an early career researcher and data scientist. I also wrote a more [technical blog post](https://gretatimaite.netlify.app/publication/rstudio_for_blogging/) for building a personal website, which was published on Dataquest Direct for aspiring data scientists. Both blog posts are of contrasting topics and underwent different levels of editorial scrutiny, which taught me tailoring my message for an audience.

I believe that being a Student Blogger will provide me with a platform to share my experience and knowledge and get in touch with those to whom it might be eye-opening, encouraging, and important. Thus, I cannot wait to discuss with you how we could achieve this together.


